version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord.js
    versions:
    - 12.5.1
    - 12.5.2
  - dependency-name: chrono-node
    versions:
    - 2.1.11
    - 2.2.0
    - 2.2.1
    - 2.2.3
    - 2.2.4
    - 2.2.5
  - dependency-name: lodash
    versions:
    - 4.17.20
